[package]
name = "satdoku"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dev-dependencies]
test-case = "*"
criterion = "*"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
